src/Entity/Season.php
<?php

namespace App\Entity;

use App\Repository\SeasonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SeasonRepository::class)
 */
class Season
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\Column(type="float")
     */
    private $discount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }
}

src/Form/SeasonType.php
<?php

namespace App\Form;

use App\Entity\Season;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeasonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('start_date')
            ->add('end_date')
            ->add('discount')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Season::class,
        ]);
    }
}

src/Controller/SeasonController.php
<?php

namespace App\Controller;

use App\Entity\Season;
use App\Form\SeasonType;
use App\Repository\SeasonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/season")
 */
class SeasonController extends AbstractController
{
    /**
     * @Route("/", name="season_index", methods={"GET"})
     */
    public function index(SeasonRepository $seasonRepository): Response
    {
        return $this->render('season/index.html.twig', [
            'seasons' => $seasonRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="season_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $season = new Season();
        $form = $this->createForm(SeasonType::class, $season);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($season);
            $entityManager->flush();

            return $this->redirectToRoute('season_index');
        }

        return $this->render('season/new.html.twig', [
            'season' => $season,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="season_show", methods={"GET"})
     */
    public function show(Season $season): Response
    {
        return $this->render('season/show.html.twig', [
            'season' => $season,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="season_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Season $season): Response
    {
        $form = $this->createForm(SeasonType::class, $season);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('season_index');
        }

        return $this->render('season/edit.html.twig', [
            'season' => $season,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="season_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Season $season): Response
    {
        if ($this->isCsrfTokenValid('delete'.$season->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($season);
            $entityManager->flush();
        }

        return $this->redirectToRoute('season_index');
    }
}

templates/season/_delete_form.html.twig
<form method="post" action="{{ path('season_delete', {'id': season.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ season.id) }}">
    <button class="btn">Delete</button>
</form>

templates/season/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/season/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Season{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Create new Season</h1>
    </div>
</div>
<div class="container my-4">
    <h1>Edit Season</h1>

    {{ include('season/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('season_index') }}">back to list</a>

    {{ include('season/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/season/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Season index{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Season index</h1>
    </div>
</div>
<div class="container my-4">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>Discount</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for season in seasons %}
            <tr>
                <td>{{ season.id }}</td>
                <td>{{ season.description }}</td>
                <td>{{ season.startDate ? season.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ season.endDate ? season.endDate|date('Y-m-d') : '' }}</td>
                <td>{{ season.discount }}</td>
                <td>
                    <a href="{{ path('season_show', {'id': season.id}) }}">show</a>
                    <a href="{{ path('season_edit', {'id': season.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('season_new') }}">Create new</a>
</div>
{% endblock %}

templates/season/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Season{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Create new Season</h1>
    </div>
</div>
<div class="container my-4">

    {{ include('season/_form.html.twig') }}

    <a href="{{ path('season_index') }}">back to list</a>
</div>
{% endblock %}

templates/season/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Season{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Season</h1>
    </div>
</div>
<div class="container my-4">
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ season.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ season.description }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ season.startDate ? season.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ season.endDate ? season.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Discount</th>
                <td>{{ season.discount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('season_index') }}">back to list</a>

    <a href="{{ path('season_edit', {'id': season.id}) }}">edit</a>

    {{ include('season/_delete_form.html.twig') }}
</div>
{% endblock %}