src/Entity/Extras.php
<?php

namespace App\Entity;

use App\Repository\ExtrasRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExtrasRepository::class)
 */
class Extras
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price_markup;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriceMarkup(): ?float
    {
        return $this->price_markup;
    }

    public function setPriceMarkup(float $price_markup): self
    {
        $this->price_markup = $price_markup;

        return $this;
    }
}

src/Form/RoomTypeType.php
<?php

namespace App\Form;

use App\Entity\RoomType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoomTypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('price_markup')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RoomType::class,
        ]);
    }
}

src/Controller/RoomTypeController.php
<?php

namespace App\Controller;

use App\Entity\RoomType;
use App\Form\RoomTypeType;
use App\Repository\RoomTypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/room/type")
 */
class RoomTypeController extends AbstractController
{
    /**
     * @Route("/", name="room_type_index", methods={"GET"})
     */
    public function index(RoomTypeRepository $roomTypeRepository): Response
    {
        return $this->render('room_type/index.html.twig', [
            'room_types' => $roomTypeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="room_type_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $roomType = new RoomType();
        $form = $this->createForm(RoomTypeType::class, $roomType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($roomType);
            $entityManager->flush();

            return $this->redirectToRoute('room_type_index');
        }

        return $this->render('room_type/new.html.twig', [
            'room_type' => $roomType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_type_show", methods={"GET"})
     */
    public function show(RoomType $roomType): Response
    {
        return $this->render('room_type/show.html.twig', [
            'room_type' => $roomType,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room_type_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RoomType $roomType): Response
    {
        $form = $this->createForm(RoomTypeType::class, $roomType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_type_index');
        }

        return $this->render('room_type/edit.html.twig', [
            'room_type' => $roomType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_type_delete", methods={"DELETE"})
     */
    public function delete(Request $request, RoomType $roomType): Response
    {
        if ($this->isCsrfTokenValid('delete'.$roomType->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($roomType);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_type_index');
    }
}

templates/room_type/_delete_form.html.twig
<form method="post" action="{{ path('room_type_delete', {'id': room_type.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room_type.id) }}">
    <button class="btn">Delete</button>
</form>

templates/room_type/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/room_type/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RoomType{% endblock %}

{% block body %}
    <h1>Edit RoomType</h1>

    {{ include('room_type/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('room_type_index') }}">back to list</a>

    {{ include('room_type/_delete_form.html.twig') }}
{% endblock %}

templates/room_type/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RoomType index{% endblock %}

{% block body %}
    <h1>RoomType index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Price_markup</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for room_type in room_types %}
            <tr>
                <td>{{ room_type.id }}</td>
                <td>{{ room_type.description }}</td>
                <td>{{ room_type.priceMarkup }}</td>
                <td>
                    <a href="{{ path('room_type_show', {'id': room_type.id}) }}">show</a>
                    <a href="{{ path('room_type_edit', {'id': room_type.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('room_type_new') }}">Create new</a>
{% endblock %}

templates/room_type/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RoomType{% endblock %}

{% block body %}
    <h1>Create new RoomType</h1>

    {{ include('room_type/_form.html.twig') }}

    <a href="{{ path('room_type_index') }}">back to list</a>
{% endblock %}

templates/room_type/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RoomType{% endblock %}

{% block body %}
    <h1>RoomType</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ room_type.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ room_type.description }}</td>
            </tr>
            <tr>
                <th>Price_markup</th>
                <td>{{ room_type.priceMarkup }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('room_type_index') }}">back to list</a>

    <a href="{{ path('room_type_edit', {'id': room_type.id}) }}">edit</a>

    {{ include('room_type/_delete_form.html.twig') }}
{% endblock %}